require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.1

  Exclude:
    - .git/**/*
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

# コメントはASCII文字で記述 => disable
Style/AsciiComments:
  Enabled: false

# ["a", "b", "c"] は %w表記にて記述 => disable
Style/WordArray:
  Enabled: false

# [:a, :b, :c] は %i表記にて記述 => disable
Style/SymbolArray:
  Enabled: false

# Layout/LineLength:
#   Max: 80

# RSpec/ContextWording:
#   Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Metrics/BlockLength:
 Exclude:
   - "spec/**/*"
