---
include:
  - "**/*.rb"
exclude:
  - '**/.bundle/**/*'
  - '**/spec/**/*'
  - '**/log/**/*'
  - '**/tmp/**/*'
require: []
domains: []
# reporters:
# - rubocop
# - require_not_found
require_paths: []
max_files: 3000
